# set Active Profiles in Configurations to "dev" (in IntelliJ)
# if no active profile set, spring defaults to h2 db as specified in application-default.properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/joe_dev
    username: joe_dev
    password: doe
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
# to generate the db schema as joe-database-create-sql in root-folder
# and use commands in sql to generate corresponding tables (one of multiple methods)
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create-mysql-db.sql