spring:
  datasource:
    url: jdbc:mysql://localhost:3306/joe_prod
    username: joe_prod
    password: doe
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false